Assets and Credits

Low Poly Computer = https://skfb.ly/6B96E

Animated Fan = https://skfb.ly/6xYr7

Desk = https://skfb.ly/6ZJYs

Bookstore = https://skfb.ly/6UKRL

Room = https://skfb.ly/6sZXt

Desk + PC = https://skfb.ly/6TCOK

Bookshelf = https://skfb.ly/DQGL

House interior = https://skfb.ly/6FPuN

Key card = https://skfb.ly/6XBFV

Floppy disk = https://skfb.ly/6XnUu

File cabinet = https://skfb.ly/6R9ZR

Safe = https://skfb.ly/6Dr6C

Note/Letter = https://skfb.ly/6pPxA


